# Generated by Django 5.0.6 on 2024-06-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание темы'),
        ),
    ]
