# Generated by Django 5.0.6 on 2024-06-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_theme_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tests/theme'),
        ),
    ]
