# Generated by Django 5.0.6 on 2024-06-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_theme_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='ticket',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='tests.ticket', verbose_name='Билет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tests/test', verbose_name='Фото к вопросу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_kg',
            field=models.TextField(verbose_name='Вопрос на кыргызском'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_ru',
            field=models.TextField(verbose_name='Вопрос на русском'),
        ),
    ]
