# Generated by Django 5.0.6 on 2024-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_ticket_questions_question_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ на кыргызском'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос на кыргызском'),
        ),
    ]
