# Generated by Django 5.1.7 on 2025-03-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_question_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Фото к вопросу'),
        ),
    ]
