# Generated by Django 5.1.7 on 2025-03-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_question_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='Фото к вопросу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tests/test', verbose_name='Фото к вопросу'),
        ),
    ]
