# Generated by Django 5.1.7 on 2025-03-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_question_photo_url_alter_question_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='Фото к вопросу (URL)'),
        ),
    ]
